-- Karemux veritabani semasi
-- 26 Agustos 2026'da canli DB'den otomatik cekildi (information_schema.columns)

-- abonelikler
--   id: integer NOT NULL DEFAULT nextval('abonelikler_id_seq'::regclass)
--   kullanici_id: integer
--   plan: text NOT NULL
--   durum: text NOT NULL DEFAULT 'aktif'::text
--   iyzico_abonelik_id: text
--   baslangic: timestamp with time zone DEFAULT now()
--   bitis: timestamp with time zone
--   kaynak: text NOT NULL DEFAULT 'bireysel'::text
--   kurum_lisans_id: integer

-- banka_hesaplari
--   id: integer NOT NULL DEFAULT nextval('banka_hesaplari_id_seq'::regclass)
--   hesap_adi: text NOT NULL
--   tur: text NOT NULL
--   banka_adi: text
--   iban: text
--   baslangic_bakiyesi: numeric NOT NULL DEFAULT 0
--   aktif: boolean NOT NULL DEFAULT true
--   olusturulma: timestamp with time zone DEFAULT now()

-- bilgi_parcalari
--   id: integer NOT NULL DEFAULT nextval('bilgi_parcalari_id_seq'::regclass)
--   ders: text NOT NULL
--   sinif: integer
--   unite: text
--   alt_konu: text
--   icerik: text NOT NULL
--   embedding: USER-DEFINED
--   kaynak: text
--   olusturulma: timestamp with time zone DEFAULT now()

-- canli_ders_katilimcilari
--   id: integer NOT NULL DEFAULT nextval('canli_ders_katilimcilari_id_seq'::regclass)
--   oturum_id: integer
--   ogrenci_id: integer
--   odendi: boolean NOT NULL DEFAULT false
--   katilim_tarihi: timestamp with time zone DEFAULT now()

-- canli_ders_oturumlari
--   id: integer NOT NULL DEFAULT nextval('canli_ders_oturumlari_id_seq'::regclass)
--   tur: text NOT NULL
--   ogretmen_id: integer
--   ders: text NOT NULL
--   konu: text
--   baslangic_zamani: timestamp with time zone NOT NULL
--   sure_dk: integer NOT NULL DEFAULT 60
--   oturum_sayisi: integer NOT NULL DEFAULT 1
--   oturum_araligi_gun: integer NOT NULL DEFAULT 0
--   max_kapasite: integer NOT NULL
--   fiyat_tl: numeric NOT NULL
--   ogretmen_payi_tl: numeric NOT NULL
--   jitsi_link: text NOT NULL
--   jitsi_oda_id: text NOT NULL
--   durum: text NOT NULL DEFAULT 'planlandi'::text
--   olusturulma: timestamp with time zone DEFAULT now()

-- cari_hareketleri
--   id: integer NOT NULL DEFAULT nextval('cari_hareketleri_id_seq'::regclass)
--   cari_id: integer NOT NULL
--   tur: text NOT NULL
--   tutar_tl: numeric NOT NULL
--   aciklama: text
--   tarih: date DEFAULT CURRENT_DATE
--   olusturulma: timestamp with time zone DEFAULT now()

-- cariler
--   id: integer NOT NULL DEFAULT nextval('cariler_id_seq'::regclass)
--   ad: text NOT NULL
--   tur: text NOT NULL
--   telefon: text
--   eposta: text
--   notlar: text
--   olusturulma: timestamp with time zone DEFAULT now()

-- finansal_hedefler
--   id: integer NOT NULL DEFAULT nextval('finansal_hedefler_id_seq'::regclass)
--   yil: integer NOT NULL
--   ay: integer NOT NULL
--   gelir_hedefi_tl: numeric NOT NULL DEFAULT 0
--   gider_hedefi_tl: numeric NOT NULL DEFAULT 0
--   notlar: text
--   olusturulma: timestamp with time zone DEFAULT now()

-- geri_bildirimler
--   id: integer NOT NULL DEFAULT nextval('geri_bildirimler_id_seq'::regclass)
--   kullanici_id: integer
--   ozellik: text NOT NULL
--   tur: text NOT NULL
--   mesaj: text
--   olusturulma: timestamp with time zone DEFAULT now()

-- giderler
--   id: integer NOT NULL DEFAULT nextval('giderler_id_seq'::regclass)
--   kategori: text NOT NULL
--   tutar_tl: numeric NOT NULL
--   aciklama: text
--   tarih: date NOT NULL DEFAULT CURRENT_DATE
--   tekrarlayan: boolean NOT NULL DEFAULT false
--   olusturulma: timestamp with time zone DEFAULT now()

-- gunluk_gorevler
--   id: integer NOT NULL DEFAULT nextval('gunluk_gorevler_id_seq'::regclass)
--   kullanici_id: integer
--   cihaz_id: text
--   hafta_baslangic: date NOT NULL
--   gun: text NOT NULL
--   ders: text NOT NULL
--   gorev: text NOT NULL
--   kaynak: text NOT NULL DEFAULT 'koc'::text
--   tamamlandi: boolean NOT NULL DEFAULT false
--   olusturulma: timestamp with time zone DEFAULT now()

-- gunluk_kullanim
--   id: integer NOT NULL DEFAULT nextval('gunluk_kullanim_id_seq'::regclass)
--   kullanici_id: integer
--   tarih: date NOT NULL DEFAULT CURRENT_DATE
--   ai_istek_sayisi: integer NOT NULL DEFAULT 0
--   gorsel_soru_sayisi: integer NOT NULL DEFAULT 0

-- guvenlik_denemeleri
--   id: integer NOT NULL DEFAULT nextval('guvenlik_denemeleri_id_seq'::regclass)
--   anahtar: text NOT NULL
--   tur: text NOT NULL
--   basarili: boolean NOT NULL DEFAULT false
--   olusturulma: timestamp with time zone DEFAULT now()

-- hata_kitapcigi
--   id: integer NOT NULL DEFAULT nextval('hata_kitapcigi_id_seq'::regclass)
--   kullanici_id: integer
--   cihaz_id: text
--   ders: text NOT NULL
--   alt_konu: text
--   soru: text NOT NULL
--   secenekler: jsonb NOT NULL
--   dogru_index: integer NOT NULL
--   verilen_index: integer
--   aciklama: text
--   cozuldu: boolean NOT NULL DEFAULT false
--   sonraki_tekrar: date DEFAULT (CURRENT_DATE + 1)
--   tekrar_asamasi: integer NOT NULL DEFAULT 0
--   olusturulma: timestamp with time zone DEFAULT now()

-- ilerleme
--   id: integer NOT NULL DEFAULT nextval('ilerleme_id_seq'::regclass)
--   kullanici_id: integer
--   ders: text NOT NULL
--   konu: text NOT NULL
--   dogru_sayisi: integer
--   toplam_soru: integer
--   olusturulma: timestamp with time zone DEFAULT now()

-- imha_kayitlari
--   id: integer NOT NULL DEFAULT nextval('imha_kayitlari_id_seq'::regclass)
--   anonim_referans: text NOT NULL
--   islem_turu: text NOT NULL
--   islem_tarihi: timestamp with time zone NOT NULL DEFAULT now()
--   islem_sonucu: text NOT NULL
--   silinen_veri_kategorileri: text
--   anonimlestirme_yapildi_mi: boolean NOT NULL
--   tetikleyen_olay: text

-- kariyer_basvurulari
--   id: integer NOT NULL DEFAULT nextval('kariyer_basvurulari_id_seq'::regclass)
--   ad: text NOT NULL
--   eposta: text NOT NULL
--   telefon: text
--   basvuru_turu: text NOT NULL
--   departman: text NOT NULL
--   deneyim_yili: integer
--   egitim_seviyesi: text
--   egitim_alani: text
--   portfolyo_url: text
--   ozgecmis_metni: text
--   adli_sicil_beyani: boolean NOT NULL DEFAULT false
--   bilgi_dogrulugu_beyani: boolean NOT NULL DEFAULT false
--   durum: text NOT NULL DEFAULT 'beklemede'::text
--   admin_notu: text
--   basvuru_tarihi: timestamp with time zone DEFAULT now()
--   degerlendirme_tarihi: timestamp with time zone

-- kasa_hareketleri
--   id: integer NOT NULL DEFAULT nextval('kasa_hareketleri_id_seq'::regclass)
--   hesap_id: integer NOT NULL
--   tur: text NOT NULL
--   tutar_tl: numeric NOT NULL
--   aciklama: text
--   tarih: date DEFAULT CURRENT_DATE
--   olusturulma: timestamp with time zone DEFAULT now()

-- kullanici_kredileri
--   kullanici_id: integer NOT NULL
--   kalan_kredi: integer NOT NULL DEFAULT 0
--   guncellenme: timestamp with time zone DEFAULT now()

-- kullanicilar
--   id: integer NOT NULL DEFAULT nextval('kullanicilar_id_seq'::regclass)
--   eposta: text NOT NULL
--   sifre_hash: text NOT NULL
--   ad: text
--   rol: text NOT NULL DEFAULT 'ogrenci'::text
--   eposta_dogrulandi: boolean NOT NULL DEFAULT false
--   dogrulama_kodu: text
--   dogrulama_kodu_son_tarih: timestamp with time zone
--   veli_baglanti_kodu: text
--   olusturulma: timestamp with time zone DEFAULT now()
--   sifre_sifirlama_kodu: text
--   sifre_sifirlama_son_tarih: timestamp with time zone
--   okul: text
--   telefon: text
--   sinif: integer
--   hedef_il: text
--   hedef_ilce: text
--   hedef_okul: text
--   hedef_puan: integer
--   kurum_id: integer
--   telegram_chat_id: text
--   telegram_baglanti_kodu: text
--   il: text
--   veli_eposta: text
--   veli_onay_verildi: boolean NOT NULL DEFAULT false
--   veli_onay_token: text

-- kurum_deneme_satin_alma
--   id: integer NOT NULL DEFAULT nextval('kurum_deneme_satin_alma_id_seq'::regclass)
--   kurum_id: integer
--   deneme_id: integer
--   tutar_tl: numeric NOT NULL
--   odendi: boolean NOT NULL DEFAULT false
--   satin_alma_tarihi: timestamp with time zone DEFAULT now()

-- kurum_lisans_satin_alma
--   id: integer NOT NULL DEFAULT nextval('kurum_lisans_satin_alma_id_seq'::regclass)
--   kurum_id: integer
--   plan: text NOT NULL
--   koltuk_sayisi: integer NOT NULL
--   tutar_tl: numeric NOT NULL
--   odendi: boolean NOT NULL DEFAULT false
--   satin_alma_tarihi: timestamp with time zone DEFAULT now()

-- kurumlar
--   id: integer NOT NULL DEFAULT nextval('kurumlar_id_seq'::regclass)
--   ad: text NOT NULL
--   kurum_kodu: text NOT NULL
--   olusturulma: timestamp with time zone DEFAULT now()
--   kisi_basi_fiyat_tl: numeric DEFAULT 300
--   min_kisi_sayisi: integer DEFAULT 20
--   vergi_no: text
--   vergi_dairesi: text
--   yetkili_unvan: text

-- mevcut_okullar
--   id: integer NOT NULL DEFAULT nextval('mevcut_okullar_id_seq'::regclass)
--   il: text NOT NULL
--   ilce: text NOT NULL
--   okul_adi: text NOT NULL
--   onaylandi: boolean NOT NULL DEFAULT false

-- odemeler
--   id: integer NOT NULL DEFAULT nextval('odemeler_id_seq'::regclass)
--   kullanici_id: integer
--   iyzico_odeme_id: text
--   tutar: numeric NOT NULL
--   para_birimi: text DEFAULT 'TRY'::text
--   durum: text NOT NULL
--   olusturulma: timestamp with time zone DEFAULT now()
--   conversation_id: text
--   plan: text
--   kurum_id: integer
--   ucretli_deneme_id: integer
--   kurum_lisans_id: integer
--   canli_ders_oturum_id: integer
--   randevu_id: integer

-- ogretmen_basvurulari
--   id: integer NOT NULL DEFAULT nextval('ogretmen_basvurulari_id_seq'::regclass)
--   ad: text NOT NULL
--   eposta: text NOT NULL
--   telefon: text
--   brans: text NOT NULL
--   kategori: text NOT NULL
--   istenen_kademe: text NOT NULL
--   deneyim_yili: integer
--   ozgecmis_metni: text
--   durum: text NOT NULL DEFAULT 'beklemede'::text
--   admin_notu: text
--   basvuru_tarihi: timestamp with time zone DEFAULT now()
--   degerlendirme_tarihi: timestamp with time zone
--   egitim_seviyesi: text
--   egitim_alani: text
--   sertifikalar: text
--   sinav_hazirlik_deneyimi: boolean DEFAULT false
--   adli_sicil_beyani: boolean DEFAULT false
--   bilgi_dogrulugu_beyani: boolean DEFAULT false
--   cv_dosya_url: text

-- ogretmen_musaitlik
--   id: integer NOT NULL DEFAULT nextval('ogretmen_musaitlik_id_seq'::regclass)
--   ogretmen_id: integer
--   haftanin_gunu: integer NOT NULL
--   baslangic_saat: time without time zone NOT NULL
--   bitis_saat: time without time zone NOT NULL

-- ogretmenler
--   id: integer NOT NULL DEFAULT nextval('ogretmenler_id_seq'::regclass)
--   ad: text NOT NULL
--   brans: text NOT NULL
--   aciklama: text
--   aktif: boolean NOT NULL DEFAULT true
--   olusturulma: timestamp with time zone DEFAULT now()
--   saatlik_ucret_tl: numeric DEFAULT 600
--   kademe: text DEFAULT 'B'::text

-- paketler
--   id: integer NOT NULL DEFAULT nextval('paketler_id_seq'::regclass)
--   anahtar: text NOT NULL
--   ad: text NOT NULL
--   fiyat_tl: numeric NOT NULL
--   sure_gun: integer
--   kredi_miktari: integer
--   aciklama: text
--   aktif: boolean NOT NULL DEFAULT true
--   olusturulma: timestamp with time zone DEFAULT now()
--   gunluk_ai_limiti: integer

-- personel
--   id: integer NOT NULL DEFAULT nextval('personel_id_seq'::regclass)
--   ad: text NOT NULL
--   eposta: text NOT NULL
--   sifre_hash: text NOT NULL
--   rol: text NOT NULL DEFAULT 'calisan'::text
--   aktif: boolean NOT NULL DEFAULT true
--   olusturulma: timestamp with time zone DEFAULT now()
--   son_giris: timestamp with time zone

-- personel_gorev
--   id: integer NOT NULL DEFAULT nextval('personel_gorev_id_seq'::regclass)
--   atanan_personel_id: integer
--   atayan_personel_id: integer
--   baslik: text NOT NULL
--   aciklama: text
--   durum: text NOT NULL DEFAULT 'acik'::text
--   oncelik: text NOT NULL DEFAULT 'normal'::text
--   son_tarih: date
--   olusturulma: timestamp with time zone DEFAULT now()
--   tamamlanma_tarihi: timestamp with time zone

-- personel_izin
--   id: integer NOT NULL DEFAULT nextval('personel_izin_id_seq'::regclass)
--   personel_id: integer NOT NULL
--   baslangic_tarihi: date NOT NULL
--   bitis_tarihi: date NOT NULL
--   tur: text NOT NULL DEFAULT 'yillik'::text
--   durum: text NOT NULL DEFAULT 'beklemede'::text
--   aciklama: text
--   talep_tarihi: timestamp with time zone DEFAULT now()
--   karar_tarihi: timestamp with time zone

-- personel_mesai
--   id: integer NOT NULL DEFAULT nextval('personel_mesai_id_seq'::regclass)
--   personel_id: integer NOT NULL
--   giris_zamani: timestamp with time zone NOT NULL DEFAULT now()
--   cikis_zamani: timestamp with time zone
--   calisma_notu: text

-- randevular
--   id: integer NOT NULL DEFAULT nextval('randevular_id_seq'::regclass)
--   ogretmen_id: integer
--   ogrenci_id: integer
--   baslangic_zamani: timestamp with time zone NOT NULL
--   bitis_zamani: timestamp with time zone NOT NULL
--   zoom_link: text
--   zoom_meeting_id: text
--   durum: text NOT NULL DEFAULT 'onaylandi'::text
--   olusturulma: timestamp with time zone DEFAULT now()
--   ucret_tl: numeric
--   odendi: boolean NOT NULL DEFAULT false
--   ogretmen_payi_tl: numeric

-- satislar
--   id: integer NOT NULL DEFAULT nextval('satislar_id_seq'::regclass)
--   kullanici_id: integer
--   paket_id: integer
--   tutar_tl: numeric NOT NULL
--   taksit_sayisi: integer NOT NULL DEFAULT 1
--   iyzico_komisyon_tl: numeric
--   net_gelir_tl: numeric
--   olusturulma: timestamp with time zone DEFAULT now()

-- seviye_tespit_kademe
--   id: integer NOT NULL DEFAULT nextval('seviye_tespit_kademe_id_seq'::regclass)
--   kullanici_id: integer
--   ders: text NOT NULL
--   unite: text NOT NULL
--   kaynak_sinif: integer NOT NULL
--   kademe: integer NOT NULL DEFAULT 1
--   tamamlandi: boolean NOT NULL DEFAULT false
--   olusturulma: timestamp with time zone DEFAULT now()

-- seviye_tespit_sonuc
--   id: integer NOT NULL DEFAULT nextval('seviye_tespit_sonuc_id_seq'::regclass)
--   kullanici_id: integer
--   toplam_soru: integer NOT NULL
--   dogru_sayisi: integer NOT NULL
--   zayif_unite_sayisi: integer NOT NULL
--   olusturulma: timestamp with time zone DEFAULT now()

-- sinav_sonuclari
--   id: integer NOT NULL DEFAULT nextval('sinav_sonuclari_id_seq'::regclass)
--   kullanici_id: integer
--   tur: text NOT NULL
--   ders: text NOT NULL
--   dogru: integer NOT NULL
--   yanlis: integer NOT NULL
--   bos: integer NOT NULL
--   net: numeric NOT NULL
--   olusturulma: timestamp with time zone DEFAULT now()

-- soru_bankasi
--   id: integer NOT NULL DEFAULT nextval('soru_bankasi_id_seq'::regclass)
--   ders: text NOT NULL
--   sinif: integer
--   unite: text
--   alt_konu: text
--   zorluk: text
--   soru: text NOT NULL
--   secenekler: jsonb NOT NULL
--   dogru_index: integer NOT NULL
--   kaynak_turu: text
--   gosterim_sayisi: integer NOT NULL DEFAULT 0
--   dogru_cevaplanma_sayisi: integer NOT NULL DEFAULT 0
--   olusturulma: timestamp with time zone DEFAULT now()
--   aciklama: text

-- talepler
--   id: integer NOT NULL DEFAULT nextval('talepler_id_seq'::regclass)
--   tur: text NOT NULL
--   baslik: text NOT NULL
--   baslik_normalize: text NOT NULL
--   aciklama: text
--   talep_sayisi: integer NOT NULL DEFAULT 1
--   ilk_talep: timestamp with time zone DEFAULT now()
--   son_talep: timestamp with time zone DEFAULT now()

-- ucretli_deneme_sonuclari
--   id: integer NOT NULL DEFAULT nextval('ucretli_deneme_sonuclari_id_seq'::regclass)
--   deneme_id: integer
--   kullanici_id: integer
--   kurum_id: integer
--   dogru: integer NOT NULL
--   yanlis: integer NOT NULL
--   bos: integer NOT NULL
--   net: numeric NOT NULL
--   olusturulma: timestamp with time zone DEFAULT now()

-- ucretli_denemeler
--   id: integer NOT NULL DEFAULT nextval('ucretli_denemeler_id_seq'::regclass)
--   ad: text NOT NULL
--   ders: text NOT NULL
--   sinif: integer NOT NULL
--   sorular: jsonb NOT NULL
--   fiyat_tl: numeric NOT NULL
--   aktif: boolean NOT NULL DEFAULT true
--   olusturulma: timestamp with time zone DEFAULT now()
--   kapsam: text NOT NULL DEFAULT 'ulusal'::text
--   il: text

-- ulusal_deneme_sonuclari
--   id: integer NOT NULL DEFAULT nextval('ulusal_deneme_sonuclari_id_seq'::regclass)
--   ulusal_deneme_id: integer
--   kullanici_id: integer
--   kurum_id: integer
--   dogru: integer NOT NULL
--   yanlis: integer NOT NULL
--   bos: integer NOT NULL
--   net: numeric NOT NULL
--   olusturulma: timestamp with time zone DEFAULT now()

-- ulusal_denemeler
--   id: integer NOT NULL DEFAULT nextval('ulusal_denemeler_id_seq'::regclass)
--   ad: text NOT NULL
--   sinif: integer NOT NULL
--   ders: text NOT NULL
--   sorular: jsonb NOT NULL
--   acilis: timestamp with time zone NOT NULL
--   kapanis: timestamp with time zone NOT NULL
--   olusturulma: timestamp with time zone DEFAULT now()

-- veli_ogrenci
--   id: integer NOT NULL DEFAULT nextval('veli_ogrenci_id_seq'::regclass)
--   veli_id: integer
--   ogrenci_id: integer
--   olusturulma: timestamp with time zone DEFAULT now()
